Repository WildCodeSchool/2023-09-PHP-LYON-P2-perle-do, pull requests merged in 2023-11, with the labels that each got.

#3 S01 us02 navbar mobile
  public/assets/css/style.css
  src/View/layout.html.twig
  src/routes.php
Labels: Changes requested

#4 S01 us04header
  composer.json
  composer.lock
  public/assets/css/style.css
  public/assets/images/logo2.png
  src/Controller/SearchController.php
  src/Model/SearchManager.php
  src/View/Home/index.html.twig
  src/View/Search/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Changes requested

#9 S01 us09 addproducts
  public/assets/css/style.css
  src/Controller/CategoryController.php
  src/View/Category/add.html.twig
Labels: Changes requested

#12 S01 us10addcutomer
  public/assets/css/style.css
  src/Controller/CategoryController.php
  src/Controller/CustomerController.php
  src/Controller/SearchController.php
  src/Controller/TypeController.php
  src/Model/CategoryManager.php
  src/Model/CustomerManager.php
  src/Model/TypeManager.php
  src/Service/ValidationService.php
  src/View/Category/add.html.twig
  src/View/Category/index.html.twig
  src/View/Customer/_form.html.twig
  src/View/Customer/add.html.twig
  src/View/Customer/edit.html.twig
  src/View/Customer/index.html.twig
  src/View/Customer/show.html.twig
  src/View/Search/index.html.twig
  src/routes.php
Labels: Needs pair review

#15 S1 us13 addcategory
  public/assets/css/style.css
  src/Controller/CategoryController.php
  src/Model/CategoryManager.php
  src/Service/ValidationCategory.php
  src/View/Category/_form.html.twig
  src/View/Category/add.html.twig
  src/View/Category/index.html.twig
Labels: Needs pair review

#17 update 7
  src/View/User/register.html.twig
Labels: Needs pair review

#19 edit category, manager and controller
  public/assets/css/style.css
  src/Controller/CategoryController.php
  src/Model/CategoryManager.php
  src/View/Category/edit.html.twig
  src/View/Category/index.html.twig
  src/View/Customer/index.html.twig
  src/View/Customer/show.html.twig
Labels: Changes done

#22 S01 us17 materialpage
  public/assets/css/style.css
  src/Controller/MaterialController.php
  src/Model/MaterialManager.php
  src/Service/ValidationService.php
  src/View/Category/index.html.twig
  src/View/Material/index.html.twig
  src/routes.php
Labels: Needs pair review

#26 show product html.twig - manager - controller -css
  public/assets/css/style.css
  src/Controller/ProductController.php
  src/Model/CustomerManager.php
  src/Model/ProductManager.php
  src/View/Customer/show.html.twig
  src/View/Product/index.html.twig
  src/View/Product/show.html.twig
Labels: Changes done

#28 S02 us04 password modification
  src/Controller/AuthController.php
  src/Controller/CategoryController.php
  src/Controller/CustomerController.php
  src/Controller/HomeController.php
  src/Controller/InvoiceController.php
  src/Controller/ProductController.php
  src/Controller/SearchController.php
  src/Controller/TypeController.php
  src/Controller/UserController.php
  src/Model/AuthManager.php
  src/Model/UserManager.php
  src/Service/UserService.php
  src/View/Auth/login.html.twig
  src/View/User/edit.html.twig
  src/View/User/form.html.twig
  src/View/User/index.html.twig
  src/View/User/register.html.twig
  src/View/User/show.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Needs pair review

#32 S02 us10 css button cart
  public/assets/css/style.css
  src/View/Category/index.html.twig
  src/View/Customer/index.html.twig
  src/View/Customer/show.html.twig
  src/View/Material/index.html.twig
  src/View/Product/index.html.twig
  src/View/Product/show.html.twig
  src/View/User/index.html.twig
  src/View/User/show.html.twig
Labels: Needs pair review

#34 S2 us07 panier
  src/Controller/ProductController.php
  src/Controller/ShopController.php
  src/Model/ShopManager.php
  src/View/Auth/login.html.twig
  src/View/Product/index.html.twig
  src/View/Shop/_form.html.twig
  src/View/Shop/add.html.twig
  src/View/Shop/edit.html.twig
  src/View/Shop/index.html.twig
  src/View/Shop/show.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: Needs pair review

#38 S2 us07 panier
  src/Controller/ShopController.php
  src/Model/InvoiceManager.php
  src/Model/PaymentManager.php
  src/Service/ValidationCart.php
  src/View/Shop/index.html.twig
Labels: Needs pair review

#37 S02 us14invoice
  composer.json
  composer.lock
  database.sql
  public/assets/css/style.css
  src/Controller/AbstractController.php
  src/Controller/CustomerController.php
  src/Controller/InvoiceController.php
  src/Controller/ShopController.php
  src/Model/InvoiceManager.php
  src/Model/ProductManager.php
  src/View/Category/index.html.twig
  src/View/Customer/show.html.twig
  src/View/Invoice/index.html.twig
  src/View/Invoice/show.html.twig
  src/View/Product/index.html.twig
  src/View/layout.html.twig
Labels: Changes requested

#43 S02 us19jsfunction discount
  public/assets/script.js
  src/Model/InvoiceManager.php
  src/View/Customer/show.html.twig
  src/View/Shop/index.html.twig
Labels: Needs pair review
